[package]
name = "tts-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
const_format = "0.2.35"
open = "5.3.3"
tempfile = "3.24.0"
voicevox_core = { git = "https://github.com/VOICEVOX/voicevox_core.git", tag = "0.16.3", version = "0.0.0", features = ["load-onnxruntime"] }
